# Generated by Django 4.0.4 on 2022-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('directeur', models.CharField(max_length=100)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('duree', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('acteur', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
