# Generated by Django 4.0.4 on 2022-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Titre', '0002_rename_titre_titre_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titre',
            old_name='nom',
            new_name='titre',
        ),
    ]
