# Generated by Django 4.0.4 on 2022-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titre', '0003_rename_nom_titre_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
